import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Navbar from "../_components/Navbar";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: {
    locale: string;
  };
};

export default async function RootLayout({children, params}: Props) {
  const {locale} = await params;
  console.log("Locale is : " , locale);

  let messages;
  try {
    messages = (await import(`../../../messages/${locale}.json`)).default;
    console.log("Messages: " , messages);
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
        <Navbar />
        {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
